In [ ]:
import sys

suNo, quizNo = map(int, input().split())
numbers = list(map(int, input().split()))
prefix_sum = [0]
temp = 0

for i in numbers:
    temp = temp + i
    prefix_sum.append(temp) # 합 배열 만들기

for i in range(quizNo):
    s, e = map(int, input().split())
    print(prefix_sum[e] - prefix_sum[s-1])

12
9
1


![image.png](attachment:image.png)

![image.png](attachment:image.png)

![image.png](attachment:image.png)

In [ ]:
# 1. n 배열(리스트)의 크기, m 질의의 개수 입력
# 2. A 배열에 대한 값, D 배열에 대한 합
# 3 for문을 통해 A 배열의 값들 입력
# 4 for문을 통해 D 배열의 합계 입력
# 5. m 질의의 개수만큼 for문을 돌면서 결과 출력


# 2차원 배열 크기 및 구간 합 질의 갯수 입력
n, m = map(int, input().split())
A = [[0] * (n + 1)]
D = [[0] * (n + 1) for _ in range(n + 1)]

# print(A, D)

In [ ]:
# A 배열 데이터 생성
for i in range(n):
    A.append([0] + list(map(int, input().split()))) #

print(A)

In [ ]:
# D 합계 배열 생성
for i in range(1, n + 1):
    for j in range(1, n + 1):
        # 합 배열 생성
        D[i][j] = D[i][j - 1] + D[i - 1][j] - D[i - 1][j - 1] + A[i][j]

print(D)

[[0, 0, 0, 0, 0], [0, 1, 3, 6, 10], [0, 3, 8, 15, 24], [0, 6, 15, 27, 42], [0, 10, 24, 42, 64]]


In [ ]:
# 구간 배열 결과 출력
for i in range(m):
    x1, y1, x2, y2 = map(int, input().split())
    # 구간 합 배열로 질의 결과 출력
    result = D[x2][y2] - D[x1-1][y2] - D[x2][y1-1] + D[x1-1][y1-1]
    print(result)

27
6
64
45


In [ ]:
# 데이터 경과 확인용(실전에서는 필요 없음)
import numpy as np
print(np.array(A))
print()
print(np.array(D))

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  5  6  7  8]
 [ 0  9 10 11 12]
 [ 0 13 14 15 16]]

[[  0   0   0   0   0]
 [  0   1   3   6  10]
 [  0   6  14  24  36]
 [  0  15  33  54  78]
 [  0  28  60  96 136]]


전체 코드

In [ ]:
# 2차원 배열 크기 및 구간 합 질의 갯수 입력
n, m = map(int, input().split())
A = [[0] * (n + 1)]
D = [[0] * (n + 1) for _ in range(n + 1)]

# A 배열 데이터 생성
for i in range(n):
    A.append([0] + list(map(int, input().split())))

# D 합계 배열 생성
for i in range(1, n + 1):
    for j in range(1, n + 1):
        # 합 배열 생성
        D[i][j] = D[i][j - 1] + D[i - 1][j] - D[i - 1][j - 1] + A[i][j]

# 구간 배열 결과 출력
for i in range(m):
    x1, y1, x2, y2 = map(int, input().split())
    # 구간 합 배열로 질의 결과 출력
    result = D[x2][y2] - D[x1-1][y2] - D[x2][y1-1] + D[x1-1][y1-1]
    print(result)

1
2
3
4


혼자 해보세요...교재 답은 나중에 참조하세요

![image.png](attachment:image.png)